version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
    environment:
      - DB_HOST=db

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: shoplist_db
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
